Fix issue with wrong values for overlapping bed-ranges
38/d4-format pull request #84
Opened 2024-08-23 11:49 UTC by Jakob37

As a part of testing #83, we realized that some values were used multiple times in calculations.

Tracking this down, it seems that in `track.rs`, same ranges were used multiple times. This is the part of the code I recently updated to fix a separate issue, and might have been a new bug caused by solving the old.

I have prepared a 10nt `d4` file mapped with two reads to test this:

```
$ d4tools show input_10nt.d4
chr     0       3       0
chr     3       4       1
chr     4       7       2
chr     7       9       1
chr     9       10      0
```

Expected total coverage would be `(3 * 2 + 3 * 1) / 10 = 0.9`

Before the update:

```
$ d4tools stat -s mean -r input_10nt.overlapping_ranges.bed input_10nt.d4
chr     0       10      1.2
chr     4       5       2
```

After the change:

```
$ d4tools stat -s mean -r input_10nt.overlapping_ranges.bed input_10nt.d4
chr     0       10      0.9
chr     4       5       2
```

I have prepared a unit test based on this as part of the PR. This and other tests are succeeding, except two `remote-view` tests (which I don't think are related to this change).

<img width="424" alt="tests_2" src="https://github.com/user-attachments/assets/886dae05-615c-45a6-a18f-7cd21540de15">

Would you be able to review @brentp ?

2024-08-23 15:04 UTC, brentp requested changes

2024-08-23 15:04 UTC, brentp commented on d4/src/d4file/track.rs
> +                let this_begin;
```rust
let this_begin = top.get_range().0.max(last_end)
```

2024-08-23 15:04 UTC, brentp commented on d4/src/d4file/track.rs
> +                let this_begin;
```rust
let this_begin = top.get_range().0.max(last_end)
```

2024-08-23 15:04 UTC, brentp commented on d4tools/test/stat/mean-multiple-ranges/output.txt
> +chr	0	10	0.9
while we're here, can you also add, so we have the more general case of something like:
```
chr 0 10 0.9
chr 0 10 0.5
chr 0  8   0.8
chr 1 6 0.6
chr 4 5 2
```
to make sure everything is handled properly?

2024-08-26 06:08 UTC, Jakob37 commented
Thank you for the review @brentp ! Makes much sense to do more careful testing. 

I added a more extensive case and simplified the code as suggested.

Ready for re-review.

2024-08-26 16:13 UTC, brentp approved these changes

2024-08-26 16:13 UTC, merged